package com.casino.user.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "affiliate_referrals", indexes = {
    @Index(name = "idx_referral_affiliate", columnList = "affiliateId"),
    @Index(name = "idx_referral_user", columnList = "referredUserId")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AffiliateReferral {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @Column(nullable = false)
    private String affiliateId;

    @Column(nullable = false)
    private String referredUserId;

    private String affiliateCode; // Code used for referral

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ReferralStatus status;

    // Tracking
    private String ipAddress;
    private String userAgent;
    private String clickId; // Tracking ID from affiliate link
    private String trafficSource;

    // Revenue tracking
    @Column(precision = 19, scale = 2, nullable = false)
    private BigDecimal totalRevenue = BigDecimal.ZERO; // Revenue generated by this referral

    @Column(precision = 19, scale = 2, nullable = false)
    private BigDecimal totalCommission = BigDecimal.ZERO; // Commission earned from this referral

    private LocalDateTime firstDepositAt;
    private LocalDateTime lastActivityAt;

    @Column(nullable = false)
    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    public enum ReferralStatus {
        PENDING,        // Registered but no deposit
        ACTIVE,         // Made deposit and active
        INACTIVE,       // No activity for 30+ days
        CHURNED         // Permanently inactive
    }
}
